name: Deploy Website

on:
  push:
    branches:
      - ci/fix-website-deployment
    paths:
      - website/**

jobs:
  deploy_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./website
        run: |-
          yarn

      - name: Linting and typechecks
        working-directory: ./website
        run: |-
          yarn lint
          yarn typecheck

      - name: Deploy via Vercel
        uses: ./.github/actions/custom-actions/deploy-vercel
        with:
          working-directory: ./website
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-token: ${{ secrets.VERCEL_TOKEN}}
          is-production: true
          add-comment: false
